stretch_gripper_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - finger_joint
  allow_partial_joints_goal: true

  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10
